baseURL = "https://adithya-kallaje.github.io/"
title = "Adithya Kallaje - Cybersecurity Portfolio"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
# Disqus comments disabled for now
# shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Adithya Kallaje"
  info = "Aspiring Cybersecurity Professional"
  description = "Adithya Kallaje's cybersecurity portfolio showcasing projects, learning journey, and technical skills"
  keywords = "cybersecurity,infosec,student,portfolio,btech,security projects"
  avatarurl = "images/avatar.jpg"
  #gravatar = "adikallaje05@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/adithya-kallaje/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/adithya-kallaje-623b31188/"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:adikallaje05@gmail.com"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url  = "projects/"
[[menu.main]]
  name = "Writeups"
  weight = 3
  url  = "writeups/"